### ISSUE TITLE
How can we run this?

### ISSUE THREAD

**Issue by rekire** [googlecreativelab/arexperiments-portal-painter#1]
Well maybe this is a dump question, but how can we compile and run this example? I see no build files and no explanation how to compile this example.

**Comment by friej715** [comment]
The most essential instructions are under [Develop](https://github.com/googlecreativelab/arexperiments-portal-painter#develop) in the readme. A bit more detail:

This repo is the Unity project (i.e., not a .unitypackage, that's a whole other process) for Portal Painter. You'll need Unity and several other pieces of software (Android Studio, Android Build Support, ARCore SDK, ARCore Service, etc.) to develop with it and run it on your device (list of supported devices [here](https://developers.google.com/ar/discover/#supported_devices)). All those instructions are [here](https://developers.google.com/ar/develop/unity/getting-started).

You can follow those instructions almost verbatim, except that instead of creating a new project, you should download/clone this project and open it in Unity. 

From there, you'll want to make sure you're in the Main scene. You will get some errors at first, because we don't include the ARCore UnityPackage--once you download and import that in, everything should be back to normal. 

You'll also want to switch your platform (as it says under Configure the Build Settings) and make sure your Main scene is in your build. The other build settings should already be in place (although it's always a good idea to double-check).

After that, you should be able to pick up from Prepare Your Device in the other tutorial. Once you get it running, you can mess with it and add your own worlds (those instructions are back in the readme).

Closing this issue, but feel free to open a new one if you run into specific issues along the way!

**Comment by tjerkw** [comment]
I got it running, however i cant add portals to the world :p

**Comment by tjerkw** [comment]
I think i got it working, however the portal is drifting, and walls are not correctly aligned with the plane.

These are the correct settings:
![screen shot 2017-10-06 at 10 25 39](https://user-images.githubusercontent.com/818865/31269454-c3dd81e6-aa80-11e7-89e7-0b9f600eaf7e.png)

**Comment by tjerkw** [comment]
Takeaways:

- Dont forget to increase the "Brush Radius" and to assign the Portal object.
- Add the Worlds and Skyboxes to make it work!
